FROM node:23-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY .husky/install.mjs ./.husky/
RUN npm ci

COPY . .
COPY next.config.ts ./next.config.ts

EXPOSE 3000

CMD ["npm", "run", "dev"]
